config/routes.rb
Rails.application.routes.draw do
  resources :favorites
  get "signin" => 'sessions#new'

  resource :session
  get 'signup' => "users#new"
  resources :users
  root "movies#index"
  resources :movies do
    resources :reviews
  end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  RATINGS =  %w(G PG PG-13 R NC-17)

  validates :title, :released_on, :duration, presence: true
  validates :description , length: {minimum: 25}
  validates :total_gross, numericality: {greater_than_or_equal_to: 0}
  validates :image_file_name, allow_blank: true, format: {
    with: /\w+\.(gif|jpg|png)\z/i,
    message: "Must reference a GIF, JPG, or PNG file"
  }
  validates :rating, inclusion: {in: RATINGS}

  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :fans, through: :favorites, source: :user

  def self.released
    where("released_on <= ?", Time.now).order("released_on desc")
  end

  def self.hits
    where('total_gross >= 300000000').order('total_gross desc')
  end

  def self.flops
    where('total_gross < 10000000').order('total_gross asc')
  end

  def self.recently_added
    order('created_at desc').limit(3)
  end

  def flop?
    total_gross.blank? || total_gross < 50000000
  end

  def average_stars
    reviews.average(:stars)
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  
  validates :comment, length: {minimum: 4}
  STARS = [1,2,3,4,5]
  validates :stars, inclusion: { in: STARS, message: "Must be between 1 and 5"}

  belongs_to :movie
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true,
                    format: /\A\S+@\S+\z/,
                    uniqueness: {case_sensitive: false}
  validates :password, length: { minimum: 6, allow_blank: true }
  validates :username, presence: true,
                     format: /\A[A-Z0-9]+\z/i,
                     uniqueness: { case_sensitive: false }
   has_many :reviews, dependent: :destroy
   has_many :favorites, dependent: :destroy
   has_many :favorite_movies, through: :favorites, source: :movie

  def gravatar_id
  	Digest::MD5::hexdigest(email.downcase)
  end

  def self.authenticate(email, password)
    user = User.find_by(email: email)
    user && user.authenticate(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 private

  def require_signin
    unless current_user
      session[:intended_url] = request.url
      redirect_to new_session_url, alert: "Please Sign In first!"
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def current_user?(user)
    current_user == user
  end

  helper_method :current_user?

  def require_admin
    unless current_user_admin?
      redirect_to root_url, alert: "Unauthorized access"
    end
  end

  def current_user_admin?
    current_user && current_user.admin?
  end

  helper_method :current_user_admin?
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :require_signin, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]
  def index
    @movies = Movie.released
  end

  def show
    @movie = Movie.find(params[:id])
    @fans = @movie.fans
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to @movie, notice: "Movie Succesfully updated"
    else
      render :edit
    end
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie, notice: "Movie Successfully created"
    else
      render :new
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_url, alert: "Movie Successfully Deleted"
  end

private

  def movie_params
    params.require(:movie).permit(:title, :description, :rating, :released_on, :total_gross, :cast, :director, :duration, :image_file_name)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :require_signin
  before_action :set_movie


  def index
    @reviews = @movie.reviews
  end

  def new
    @review = @movie.reviews.new
  end

  def create
    @review = @movie.reviews.new(review_params)
    @review.user = current_user
    if @review.save
      redirect_to movie_reviews_path(@movie), notice: "Your Review was Succesfully Posted"
    else
      render :new
    end
  end

  def edit
    @review = @movie.reviews.find(params[:id])
  end

  def update
    @review = @movie.reviews.find(params[:id])
    if @review.update(review_params)
      redirect_to movie_reviews_path(@movie), notice: "Review Succesfully updated"
    else
      render :edit
    end
  end

  def destroy
   @review = @movie.reviews.find(params[:id])
   @review.destroy
   redirect_to movie_reviews_path(@movie), alert: "Review Successfully Deleted"
  end

  private

  def review_params
    params.require(:review).permit(:comment, :stars)
  end

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome back, #{user.name}"
      redirect_to(session[:intended_url] || user)
      session[:intended_url] = nil
    else
      flash.now[:alert] = "Invalid email/password combination!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "You have successfully signed out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :require_signin, except: [:new, :create]
	before_action :require_correct_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]
	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(set_user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to user_path(@user), notice: "You have successfully Signed Up. Welcome!!"
		else
			render :new
		end
	end

	def show
		@user = User.find(params[:id])
		@reviews = @user.reviews
		@favorite_movies = @user.favorite_movies
	end

	def edit
	end

	def update
		if @user.update(set_user_params)
			redirect_to user_path(@user), notice: "Account successfully Updated!"
		else
			render :edit
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to root_path, alert: "You have successfully deleted your account"
	end

	private

	def set_user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation, :username)
	end

	def require_correct_user
		@user = User.find(params[:id])
		redirect_to root_url unless current_user?(@user)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
 def format_total_gross(movie)
   if movie.flop?
    content_tag(:strong, 'Flop!')
   else
     number_to_currency(movie.total_gross)
   end
 end

 def image_for(movie)
   if movie.image_file_name.blank?
     image_tag('placeholder.png')
   else
     image_tag(movie.image_file_name)
   end
 end


   def format_average_stars(movie)
     if movie.average_stars.nil?
       content_tag(:strong, 'No reviews')
     else
       pluralize(number_with_precision(movie.average_stars, precision: 1) , 'star')
     end
   end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def profile_image_for(user, options={})
		size = options[:size] || 80
		url = "https://secure.gravatar.com/avatar/#{user.gravatar_id}"
		image_tag(url, alt: user.name)
	end
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2015
      <%= link_to 'Made by Suyesh Bhandari', 'https://www.suyesh.com' %>
  </p>
  <p>
    For educational purposes only.   <%= link_to 'The Pragmatic Studio', 'http://pragmaticstudio.com' %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
  <div id="masthead">
    <h1><%= link_to 'Flixters', root_path %></h1>
    <nav>
  <p>
    <% if current_user %>
       <%= link_to current_user.name.capitalize, current_user%>
       <%= link_to "Account Settings", edit_user_path(current_user), class: "button" %>
       <%= link_to 'Sign Out', session_path, method: :delete, class: 'button' %>
    <% else %>
      <%= link_to 'Sign Up', signup_path, class: 'button' %>
      <%= link_to 'Sign In', signin_path, class: 'button' %>
    <%end%>
  </p>
</nav>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <li class="all-movies">
        <%= link_to 'All Movies', movies_path, class: 'button' %>
      </li>
      <% if current_user_admin? %>
      <li class="create-movie">
        <%= link_to 'Add New Movie', new_movie_path, class: 'button' %>
      </li>
      <%end%>
    </ul>
  </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flix</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>

<div id="wrapper">
  <% if flash[:notice] %>
      <p class="flash notice">
        <%= flash[:notice] %>
      </p>
    <% elsif flash[:alert] %>
       <p class="flash alert">
         <%= flash[:alert] %>
       </p>
    <% end %>

  <div id="container">
    <section id="sidebar">
      <%= render "layouts/sidebar" %>
    </section>
    <section id="content">
      <%= yield %>
    </section>
  </div>

</div>

<%= render "layouts/footer" %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
<%= render 'shared/errors', object: @movie%>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :description %>
        <%= f.text_area :description, cols: 40, rows: 7 %>
      </li>
      <li class="required">
        <%= f.label :rating %>
        <%= f.select :rating, Movie::RATINGS, prompt: "Pick one" %>
      </li>
      <li class="required">
        <%= f.label :released_on %>
        <%= f.date_select :released_on %>
      </li>
      <li class="required">
        <%= f.label :total_gross %>
        <%= f.number_field :total_gross %>
      </li>
      <li class="required">
        <%= f.label :duration %>
        <%= f.text_field :duration, size: 10 %>
      </li>
      <li class="required">
        <%= f.label :image_file_name %>
        <%= f.text_field :image_file_name %>
      </li>
      <li>
        <%= f.label :cast %>
        <%= f.text_field :cast %>
      </li>
      <li>
        <%= f.label :director %>
        <%= f.text_field :director %>
      </li>
    </ol>
    <p>
      <%= f.submit %>
      <%= link_to "Cancel", movies_path, class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/movies/edit.html.erb
<header id="content-header">
  <h1>Editing <%= @movie.title %></h1>
</header>

<%= render 'form' %>

app/views/movies/index.html.erb
<ul id="movies">
  <% @movies.each do |movie| %>
    <li>
      <article class="movie">
        <header>
          <%= image_for(movie) %>
          <h2><%= link_to movie.title, movie %> (<%= movie.released_on.year %>)</h2>
          <h3><%= movie.cast %></h3>
          <h3><%= link_to(pluralize(movie.reviews.count, "Review"), movie_reviews_path(movie)) %></h3>
        </header>
        <p>
          <%= truncate(movie.description, length: 150, separator: ' ') %>
        </p>
        <table>
          <tr>
            <th>Rating</th>
            <td><%= movie.rating %></td>
          </tr>
          <tr>
            <th>Duration</th>
            <td><%= movie.duration %></td>
          </tr>
          <tr>
            <th>Total Gross</th>
            <td><%= format_total_gross(movie) %></td>
          </tr>
        </table>
        <footer>
        </footer>
      </article>
    </li>
  <% end %>
</ul>

app/views/movies/new.html.erb
<header id="content-header">
  <h1>Create a New Movie</h1>
</header>

<%= render 'form' %>

app/views/movies/show.html.erb
<article id="movie" class="movie">
  <header>
    <%= image_for (@movie) %>
    <h1><%= @movie.title %></h1>
    <h2>Released: <%= @movie.released_on %></h2>
  </header>

  <p>
    <%= @movie.description %>
  </p>

  <h3 class="no-rule">
    <%= @movie.rating %> &bull; <%= @movie.duration %>
  </h3>
  <p>
    <%= pluralize(@fans.size, 'fan') %>
  </p>
  <p>
  <% if @fans.any? %>
    <h3>Fans</h3>
    <ul>
      <% @fans.each do |fan| %>
      <li>
        <%= profile_image_for(fan, size: 35) %>
        <%= link_to fan.name, fan %>
      </li>
      <% end %>
    </ul>
    <% end %>
  </p>

  <h3>Cast</h3>
  <p>
    <%= @movie.cast %>
  </p>

  <h3>Director</h3>
  <p>
    <%= @movie.director %>
  </p>

  <h3>Total Gross</h3>
  <p>
    <%= format_total_gross(@movie) %>
  </p>
  <h3>Average Review</h3>
   <p>
     <%= format_average_stars(@movie) %>
   </p>
  <%= link_to pluralize(@movie.reviews.size, "Review"), movie_reviews_path(@movie) %>
  <footer>
    <%= link_to "Write Review", new_movie_review_path(@movie), class: 'button ok review' %>
    <nav>
      <% if current_user_admin? %>
      <%= link_to 'Edit', edit_movie_path(@movie), class: 'button' %>
      <%= link_to 'Delete', @movie,
                  class: 'button',
                  method: :delete, data: { confirm: 'Are you sure?' } %>
      <%end%>
    </nav>
  </footer>
</article>

app/views/reviews/edit.html.erb
<header id="content-header">
  <h1>Edit Review for <%= link_to @movie.title, movie_path(@movie) %></h1>
</header>

<%= form_for([@movie, @review]) do |f| %>
<%= render 'shared/errors',object:  @review %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, size: 40, autofocus: true %>
      </li>
      <li class="required stars">
        <%= f.label :stars %>
           <% Review::STARS.each do |star| %>
              <span class="star">
                 <%= f.radio_button :stars, star %> <%= star %>
             </span>
           <% end %>
     </li>
      <li class="required">
        <%= f.label :comment %>
        <%= f.text_area :comment, cols: 80, placeholder: "What did you think?" %>
      </li>
    </ol>
    <p>
      <%= f.submit 'Update Review' %>
      <%= link_to "Cancel", @movie, class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/reviews/index.html.erb
<h1><%= pluralize(@movie.reviews.count, "Review")%> for <%= link_to @movie.title, movie_path(@movie)%></h1>

<ol id="reviews">
  <% @reviews.each do |review| %>
    <li>
      <%= profile_image_for(review.user, size: 35) %>
      <span class="review"><%= pluralize(review.stars, 'star') %></span>
      <span class="user">by <%= link_to review.user.name, review.user %></span>
      <span class="date"><%= time_ago_in_words(review.created_at) %> ago</span>
      <p>
        &quot;<%= review.comment %>&quot;
      </p>
    </li>
    <%= link_to 'Delete', [@movie, review],
                class: 'button',
                method: :delete, data: { confirm: 'Are you sure?' } %>
    <%= link_to "Edit", edit_movie_review_path(@movie, review), class: 'button' %>
  <% end %>

</ol>

app/views/reviews/new.html.erb
<header id="content-header">
  <h1>New Review for <%= link_to @movie.title, movie_path(@movie) %></h1>
</header>

<%= form_for([@movie, @review]) do |f| %>
<%= render 'shared/errors',object:  @review %>
  <fieldset>
    <ol>
      <li class="required stars">
        <%= f.label :stars %>
           <% Review::STARS.each do |star| %>
              <span class="star">
                 <%= f.radio_button :stars, star %> <%= star %>
             </span>
           <% end %>
     </li>
      <li class="required">
        <%= f.label :comment %>
        <%= f.text_area :comment, cols: 80, placeholder: "What did you think?" %>
      </li>
    </ol>
    <p>
      <%= f.submit 'Post Review' %>
      <%= link_to "Cancel", @movie, class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h2>
      Oops! The <%= object.class.name.humanize.downcase %> could not be saved. 
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render "shared/errors", object: @user %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, size: 40, autofocus: true %>
      </li>
      <li class="required">
       <%= f.label :username %>
       <%= f.text_field :username, size: 40,
                    placeholder: "Alphanumeric characters only!" %>
      </li>
      <li class="required">
        <%= f.label :email %>
        <%= f.email_field :email, size: 40 %>
      </li>
      <li class="required">
        <%= f.label :password %>
        <%= f.password_field :password, size: 40 %>
      </li>
      <li class="required">
        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation, size: 40 %>
      </li>
    </ol>
    <p>
    <% if @user.new_record? %>
      <%= f.submit "Create Account" %>
    <% else %>
      <%= f.submit "Update Account" %>
    <% end %>
    </p>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<header id="content-header">
  <h1>Edit Account</h1>
</header>

<%= render 'form' %>

app/views/users/index.html.erb
<header id="content-header">
  <h1><%=pluralize(@users.size, 'User') %></h1>
</header>

<ul id="users">
  <% @users.each do |user| %>
    <li>
    	<%= link_to user.name, user %>
    </li>
    <% end %>
</ul>

app/views/users/new.html.erb
<header id="content-header">
  <h1>Sign Up</h1>
</header>

<%= render 'form' %>

app/views/users/show.html.erb
<article id="user">
  <header>
  <%= profile_image_for(@user) %>
    <h1><%= @user.name %></h1>
    <h2><%= @user.username %></h2>
    <h2><%= mail_to(@user.email) %></h2>
    <h3>Member Since</h3>
    <p><%= @user.created_at.strftime("%B %Y")%></p>
  </header>
</article>
<% if @favorite_movies.any? %>
<h3>Favorite Movies</h3>
<ul>
  <% @favorite_movies.each do |movie| %>
  <li>
    <%= link_to movie.title, movie %>
  </li>
  <%end%>
</ul>
<%end%>
<footer>
  <nav>
    <% if current_user?(@user) %>
      <%= link_to 'Edit Account', edit_user_path(@user), class: 'button' %>
      <%end%>
    <% if current_user_admin? %>
      <%= link_to 'Delete Account', @user, method: :delete, data: {confirm: 'Are you sure?'},
                                                          class: 'button' %>
    <%end%>
  </nav>

  <% if @reviews.any? %>
  <h3>Reviews</h3>
  <ol id="reviews">
   <% @reviews.each do |review| %>
     <li>
       <%= link_to review.movie.title, review.movie %>
       <span class="review"><%= pluralize(review.stars, 'star') %></span>
       <span class="date"><%= time_ago_in_words(review.created_at) %> ago</span>
       <p>
         &quot;<%= review.comment %>&quot;
       </p>
     </li>
   <% end %>
  </ol>
<% end %>
</footer>